version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hrmsportal
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  springboot-service:
    image: neha676/backend:v2
    container_name: springboot-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hrmsportal
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 9090          # ✅ spacing योग्य
    ports:
      - "9393:9090"              # ✅ backend बाहेरून 9393 वर accessible
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    image: neha676/frontend:v2
    container_name: frontend
    ports:
      - "2200:80"
    depends_on:
      - springboot-service

volumes:
  mysql-data:
